server:
  port: 8081

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: ${server.port}
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qq_robot2?serverTimezone=GMT%2B8
    username: root
    password: abc123

dubbo:
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
  application:
    name: ${spring.application.name}
