spring:
  application:
    name: service-test
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
server:
  port: 7000

dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
