dubbo:
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
  application:
    name: ${spring.application.name}
  consumer:
    check: false
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

simbot:
  core:
    bot-resource-type: both
    action-bots: default
  component:
    mirai:
      protocol: ANDROID_PHONE
server:
  port: 8081
