dubbo:
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
  application:
    name: ${spring.application.name}

bot:
  auto-sign:
    enabled: false
  sign-count:
    enabled: true
    admins: [2237803016]

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

simbot:
  core:
    bot-resource-type: both
    action-bots: default
  component:
    mirai:
      protocol: ANDROID_WATCH
server:
  port: 8084
